version: '3.9'
services:
  db:
    container_name: 'db'
    image: postgres:14
    restart: always
    environment:
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_DATABASE=postgres
    ports:
      - "5432:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge