"""initial migration

Revision ID: 0417d756f90c
Revises: 
Create Date: 2024-01-22 15:09:26.867478

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0417d756f90c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('menu',
    sa.Column('menu_uuid', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column("submenus_count", sa.Integer(), nullable=False),
    sa.Column("dishes_count", sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('menu_uuid')
    )
    op.create_table('submenu',
    sa.Column('submenu_uuid', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column("dishes_count", sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.menu_uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('submenu_uuid'),
    sa.UniqueConstraint('menu_id')
    )
    op.create_table('dish',
    sa.Column('dish_uuid', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('submenu_id', sa.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['submenu_id'], ['submenu.submenu_uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dish_uuid'),
    sa.UniqueConstraint('submenu_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dish')
    op.drop_table('submenu')
    op.drop_table('menu')
    # ### end Alembic commands ###